### ISSUE TITLE
Getting images inside the tweet

### ISSUE THREAD

**Issue by stormstricker** [NandanDesai/TwitterScraper4J#3]
I can see that there is a `    private ArrayList<Media> media;` inside a `Tweet` class, however when I get timelines with tweets, the media list is always empty. In `Commons` it doesn't seemm to be changed at all:

```
    static List<Tweet> scrapeTweets(Document doc) throws IOException {
            ...
            ArrayList<Media> media = new ArrayList<>();
            ...  //no use of media
                               tweets.add(new Retweet(tweetID, authorUsername, tweetText, timestamp, media, mentions, hashtags, urls, retweetedBy, comment));
```
So I've looked into how to get an image myself. Consider this tweet: https://twitter.com/FatKidDeals/status/1216534839752581120. It has one image with URL =  https://pbs.twimg.com/media/EOH__ViX0AIrQLs?format=jpg&name=900x900.

You can get that URL by sending a POST request (with the Referer header) to `https://mobile.twitter.com/i/nojs_router?path=/FatKidDeals/status/1216534839752581120/photo/1`: it would return a page with 

```
<div class="card-photo">
	<div class="media">
		<img src="https://pbs.twimg.com/media/EOH__ViX0AIrQLs.jpg:small"/>
</div>
```
element.

Another way is to look at the result of the POST with Referer header request to `https://mobile.twitter.com/i/nojs_router?path=/FatKidDeals` and find this element there:

```
data-expanded-path="/FatKidDeals/status/1216534839752581120/photo/1">pic.twitter.com/NLckTFUOe5</a>
```
and send either a GET or a POST request to `pic.twitter.com/NLckTFUOe5`: it would return a page with 

```
<meta property="og:image" content="https://pbs.twimg.com/media/EOH__ViX0AIrQLs.jpg:large">
...
<div class="AdaptiveMedia-photoContainer js-adaptive-photo "
	data-image-url="https://pbs.twimg.com/media/EOH__ViX0AIrQLs.jpg"
	data-element-context="platform_photo_card" style="background-color:rgba(17,34,64,1.0);"
	data-dominant-color="[17,34,64]">
		<img data-aria-label-part src="https://pbs.twimg.com/media/EOH__ViX0AIrQLs.jpg" alt=""
      style="width: 100%; top: -0px;"
...
```
So in the end either of these too methods would get a direct link to the .jpg image: https://pbs.twimg.com/media/EOH__ViX0AIrQLs.jpg.

I was wondering if maybe I overlooked and you already do it in your library? If no, what do you think of this approach and which method (request to `https://mobile.twitter.com/i/nojs_router?path=/FatKidDeals/status/1216534839752581120/photo/1` or to `pic.twitter.com/NLckTFUOe5`) do you think would be less likely to trigger scraping defenses?

**Comment by NandanDesai** [comment]
When you call `getUserTimeline()` method, the media field will always be empty (because the page that is being scraped won't contain direct link to images). But you can call `getTweet()` method (which accepts Tweet ID as input parameter) and you will get the media link.

`TwitterScraper twitterScraper = TwitterScraper.getInstance();
  System.out.println(twitterScraper.getTweet("1216534839752581120"));`

But as mentioned in the readme file, this library

> Cannot download videos attached to tweets.
If multiple images are attached to a tweet, then this library can fetch only the first image.

In my library, GIFs attached in tweets can be downloaded as mp4 but videos can't be downloaded. I'm researching a way to download videos and multiple images attached to a tweet. 

You can join me in researching this if you are interested. Here is an excerpt from my notes on this topic:

> While fetching the non-javascript Twitter profile,
> 
> You won't be able to get
> 1) Videos in the Tweets
> 2) If there are multiple photos in the tweet, then you can only get the first photo.
> 
> What you CAN get are:
> 1) Photo in a Tweet (i.e., the first photo).
> 2) If there are videos, then you'll get a pic of a frame in that video (like a thumbnail). The whole video can't be downloaded.
> 3) If there is a GIF in the tweet, then you'll get a frame in that GIF. GIFs can be downloaded in mp4 format (this will be explained further).
> 
> 
> But, how to know if there was originally a video or a GIF in that tweet? Because we will be getting a photo in either of the case.
> 
> Here are some of my observations:
> 
> 1) If there is a video, then the thumbnail photo URL will be of the form
> https://pbs.twimg.com/ext_tw_video_thumb/1217098198319157248/pu/img/RQZALjICCIh2vcg2.jpg:small
> 
> i.e., it will contain the "ext_tw_video_thumb" part in the URL
> 
> 2) If there is a GIF in the tweet, then the thumbnail photo URL will be of the form
> https://pbs.twimg.com/tweet_video_thumb/D6d0ptGWwAAuMPq.jpg:small
> 
> i.e., it will contain the "tweet_video_thumb" part in the URL.
> Also, GIFs are directly downloadable but videos aren't. To download the GIFs (in the form of mp4),
> fetch the GIF Id, in our case it's D6d0ptGWwAAuMPq. and visit the link like this:
> https://video.twimg.com/tweet_video/D6d0ptGWwAAuMPq.mp4
> 
> The format for downloading the GIF is https://video.twimg.com/tweet_video/<GIF id>.mp4
> But you can't download a video using this method. Only applicable for GIFs.
> 
> 3) If there is a photo in the tweet, then it's URL will be of the form:
> https://pbs.twimg.com/media/D9ctg4CXsAA1zrc.jpg:small
> It will have "media" part in the URL.


You can see the above logic being applied over [here](https://github.com/NandanDesai/TwitterScraper4J/blob/b5f711486932481bfae70240e18a80ef453d4076/src/main/java/io/github/nandandesai/TweetScraper.java#L78) in `getTweet()` method to extract the media.

I have currently put the development of this project on hold because I am busy in finishing up my other project. If you are interested and have some spare time, then you can fork this project to your account, make this project your own and research on finding new ways of fetching media from Twitter. If you are able to fetch multiple images attached to the tweets, download videos or any other feature that I'm not able to implement, then you can send me a pull request if you want that to be shared. I will be very happy accepting that in this repo!!

**Comment by stormstricker** [comment]
Nice, thank you! Using the `getTweet` method and it works OK! Though the line 83 in `TweetScraper`:

```
        String imgSrc = mediaDiv.child(0).attr("src");
```
throws a `NullPointer` if the tweet is a retweet (and maybe it has to do with it also having an empty body).

**Comment by stormstricker** [comment]
So yeah, looks like it's not possible to get an image from a retweet? Say, like this one: https://twitter.com/DjNemo__/status/1217145363016097792 the `toString` would print:

```
{
  "tweetID": "1217145363016097792",
  "authorUsername": "@DjNemo__",
  "tweetText": "This is real? twitter.com/fatkiddeals/st…",
  "timestamp": "Jan 14",
  "media": [],
  "mentions": [],
  "hashtags": [],
  "urls": [https://twitter.com/fatkiddeals/status/1213903471990018053]
}
```

So the `tweetText` doesn't seem to appear fully in that endpoint? If it did, it would be possible to get the id of the retweet and by that id call `TwitterScraper.getTweet()` method.

**Comment by stormstricker** [comment]
> In my library, GIFs attached in tweets can be downloaded as mp4 but videos can't be downloaded. I'm researching a way to download videos and multiple images attached to a tweet.

> If you are able to fetch multiple images attached to the tweets

What about the two requests I've listed above? If there is endpoint `https://mobile.twitter.com/i/nojs_router?path=/FatKidDeals/status/1216534839752581120/photo/1` maybe there are `https://mobile.twitter.com/i/nojs_router?path=/FatKidDeals/status/1216534839752581120/photo/2` for tweets with two photos? Or if there is the element `data-expanded-path="/FatKidDeals/status/1216534839752581120/photo/1">pic.twitter.com/NLckTFUOe5</a>` in the timeline response page, maybe there would be several such elements for tweets with several photos?

My project right now only really needs to get the first photo, because the tweets I scrape only have one photo attached, but if I'll need to get additional medias in the future, I'll certainly make the fork! I've done my share of getting medias from another social media site and can relate to the struggle, though.

**Comment by NandanDesai** [comment]
I've fixed the NullPointerException you mentioned (issue #4 ). 

Coming to the issue where you are not getting the images for retweets,

There are 2 types of retweets.
One is the usual retweet and the other is 'retweet with comment' where you add your own comment while retweeting. 

In this library, you can get the images for usual retweets but as mentioned in To-Do list in README file, 'retweet with comment' feature has not been added to this library yet. I will add it soon. 

But meanwhile, as a workaround, if you get a 'retweet with comment' like
```
{
  "tweetID": "1217145363016097792",
  "authorUsername": "@DjNemo__",
  "tweetText": "This is real? twitter.com/fatkiddeals/st…",
  "timestamp": "Jan 14",
  "media": [],
  "mentions": [],
  "hashtags": [],
  "urls": [https://twitter.com/fatkiddeals/status/1213903471990018053]
}
```
Notice that the `tweetText` for all 'retweet with comment' types end the a URL for the original tweet that was retweeted. Here it is `https://twitter.com/fatkiddeals/status/1213903471990018053`. You can extract the tweet ID from this URL and give that to getTweet() method and you will get the tweet that was retweeted. And as I said, you will have to do this only for 'retweet with comment' types as you will get images for usual retweets from this library. 

To find if the tweet is a retweet or not, you can do something like `if(tweet instanceof Retweet)` where `Retweet` is a class defined in this library. 

Hope this helps.
