### ISSUE TITLE
Working status

### ISSUE THREAD

**Issue by Charles26** [NandanDesai/TwitterScraper4J#5]
Hi, just would like to know if this project is still working. I've  tryied it out, but not getting response from tweets posts.
Regards,

**Comment by NandanDesai** [comment]
can you please elaborate? What's the error that you're get getting? Need more details.

**Comment by Charles26** [comment]
Yes, when executing for example test file: TweetScraperTest.java, the returned list of tweets is empty.
Code:

```
TwitterScraper twitterScraper = TwitterScraper.getInstance();
List<Tweet> tweets=twitterScraper.getUserTimeline("fs0c131y");
System.out.println("Tweets: "+ tweets);  
```


Output received:
Tweets: []


I've tried with other users, but get same empty results.

**Comment by Charles26** [comment]
When I debug it, to file: TweetScraper.java, line 31:
`Document doc = Utils.getDocument(url, cookies, TweetScraper.class, proxy);`

I get html code, but not the tweets itself. 
It seems some javascripts used by Twitter are obfuscating the tweets.

**Comment by NandanDesai** [comment]
Yes. Twitter has shutdown it's legacy (non-JavaScript) version. This library used to fetch that legacy version and scrape the content. Now that the Legacy Twitter is shutdown, this library won't work. I'll be archiving this repository and putting this note in the README. Thank you so much for informing :)

And now, the only way to access Twitter content would be through it's official API. Or you may search if someone has reverse-engineered Twitter's private API (the API which is used to communicate with their official mobile apps, webpages etc.) and made a library for the same. But that would be against their T&Cs. 

I would suggest you go with their official Public API and use Twitter4J (if you're using Java) for the same.

Thank you!

**Comment by NandanDesai** [comment]
Yes. Twitter has shutdown it's legacy (non-JavaScript) version. This library used to fetch that legacy version and scrape the content. Now that the Legacy Twitter is shutdown, this library won't work. I'll be archiving this repository and putting this note in the README. Thank you so much for informing :)

And now, the only way to access Twitter content would be through it's official API. Or you may search if someone has reverse-engineered their private API (the API which is used to communicate with their official mobile apps, webpages etc.) and made a library for the same. But that would be against their T&Cs. 

I would suggest you go with their official Public API and use Twitter4J (if you're using Java) for the same.

Thank you!
